/**
 * Slide 12: Developer Personality
 * AI-generated developer archetype and traits
 */

'use client'

import React from 'react'
import { FadeInUp, TypewriterText } from '@/components/animations'
import { Sparkles } from 'lucide-react'
import type { SlideProps } from '@/lib/types'

export function Slide12Personality({ data }: SlideProps) {
  // Parse personality traits if available
  const traits = data.personality_traits || []

  return (
    <div className="slide-container">
      <div className="max-w-4xl mx-auto space-y-10">
        <FadeInUp>
          <div className="text-center space-y-4">
            <Sparkles className="h-12 w-12 mx-auto text-accent" />
            <h2 className="text-3xl md:text-4xl font-body text-foreground">
              Your Developer DNA
            </h2>
          </div>
        </FadeInUp>

        <FadeInUp delay={0.3}>
          <div className="card-theme p-10 space-y-6 text-center">
            <div className="inline-block px-6 py-3 rounded-full bg-primary/20 border-2 border-primary">
              <span className="text-2xl font-header font-bold text-primary">
                {data.developer_personality}
              </span>
            </div>

            <div className="pt-6">
              <TypewriterText
                text={data.personality_summary || `You're the ${data.developer_personality.toLowerCase()} who brings unique energy to every project.`}
                className="text-xl text-foreground/80 leading-relaxed"
                speed={30}
              />
            </div>
          </div>
        </FadeInUp>

        {traits.length > 0 && (
          <FadeInUp delay={1.5}>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
              {traits.slice(0, 6).map((trait, index) => (
                <div
                  key={index}
                  className="px-4 py-3 rounded-lg bg-accent/10 border border-accent/30 text-center"
                >
                  <span className="text-sm font-medium text-foreground">
                    {trait}
                  </span>
                </div>
              ))}
            </div>
          </FadeInUp>
        )}

        <FadeInUp delay={2}>
          <div className="text-center">
            <p className="text-sm text-foreground/40 flex items-center justify-center gap-2">
              <Sparkles className="h-4 w-4" />
              Generated by AI based on your coding patterns
            </p>
          </div>
        </FadeInUp>
      </div>
    </div>
  )
}
